# Generated by Django 4.2.6 on 2023-10-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytask',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='mytask',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mytask',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='mytask',
            old_name='Title',
            new_name='title',
        ),
    ]
