# Generated by Django 4.2.6 on 2023-10-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0002_rename_date_mytask_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='status',
            field=models.TextField(choices=[('inprogress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
