# Generated by Django 4.2.6 on 2023-10-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
