# Generated by Django 4.2.6 on 2023-10-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0006_myuser_confirmpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='confirmpassword',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
